// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Models;

[Table("orders")]
public partial class Orders
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("created_date")]
    public DateTime CreatedDate { get; set; }

    [Column("updated_date")]
    public DateTime UpdatedDate { get; set; }

    [Column("status_id")]
    public Guid StatusId { get; set; }

    [Column("user_id")]
    public Guid UserId { get; set; }
    [Column("villa_id")]
    public Guid VillaId { get; set; }

    [Column("check_in")]
    [Precision(0)]
    public DateTime CheckIn { get; set; }

    [Column("check_out")]
    [Precision(0)]
    public DateTime CheckOut { get; set; }

    [ForeignKey("StatusId")]
    [InverseProperty("Orders")]
    public virtual OrderStatus Status { get; set; } = null!;

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    public virtual Users User { get; set; } = null!;

    [ForeignKey("VillaId")]
    [InverseProperty("Orders")]
    public virtual Villa Villa { get; set; }
}