// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Models;

[Table("users")]
public partial class Users
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("login")]
    [StringLength(15)]
    public string Login { get; set; } = null!;

    [Column("first_name")]
    [StringLength(25)]
    public string FirstName { get; set; } = null!;

    [Column("last_name")]
    [StringLength(25)]
    public string LastName { get; set; } = null!;

    [Column("hashed_password")]
    public string HashedPassword { get; set; } = null!;

    [Column("role_id")]
    public Guid RoleId { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; } = null!;
}