// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DataLayer.Models;

[Table("villa_details")]
public partial class VillaDetails
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Column("rate")]
    public double Rate { get; set; }

    [Column("sqmt")]
    public double Sqmt { get; set; }

    [Column("occupancy")]
    public int? Occupancy { get; set; }

    [Column("created_date")]
    public DateTime CreatedDate { get; set; }

    [Column("updated_date")]
    public DateTime UpdatedDate { get; set; }

    [InverseProperty("VillaDetails")]
    public virtual Villa? Villa { get; set; }
}